### ISSUE TITLE
There are errors from this framework when i use docker

### ISSUE THREAD

**Issue by emjimadhu** [alosaur/alosaur#10]
I faced multiple errors from the framework when i use docker. I have attached the rror log.
[docker-error.txt](https://github.com/alosaur/alosaur/files/4236171/docker-error.txt)

**Comment by irustm** [comment]
what is your version of deno?

deno --version

**Comment by emjimadhu** [comment]
```
deno 0.30.0
v8 8.1.108
typescript 3.7.2
```

I made a sample repo https://github.com/emjimadhu/alosaur-boilerplate

1) run `yarn docker:build`
2) run `yarn docker:run`

**Comment by irustm** [comment]
fixed to latest version of node, example: https://github.com/alosaur/alosaur/blob/master/examples/docker/Dockerfile

FROM maxmcd/deno:jessie-v0.34.0

and fix 


CMD [ "deno", "run", "**-r**", ...
