### ISSUE TITLE
Accessing context state in request handler

### ISSUE THREAD

**Issue by cmd-johnson** [alosaur/alosaur#100]
`MiddlewareTarget`s have to possibility to pass data to other `MiddlewareTargets` further downstream using the `Context`'s `state` property. This could for example be used to implement a session middleware that looks the currently logged in user using a session cookie and another middleware that checks if the logged in user has permission to access a certain route.

Is there a way to access that state from within a request handler inside a controller?

**Comment by irustm** [comment]
Yes, this is how it was supposed to work. But apparently, it was overlooked. Thank you for opening this issue! It will be finished in a few hours.

**Comment by irustm** [comment]
https://github.com/alosaur/alosaur/pull/101

**Comment by irustm** [comment]
https://github.com/alosaur/alosaur/tree/master/examples/middlewares
