### ISSUE TITLE
demo  run error 

### ISSUE THREAD

**Issue by liuxiaobina** [alosaur/alosaur#11]
import { 
    Controller,
    Content,
    Get,
    Area,
    App,
  } from 'https://deno.land/x/alosaur/src/mod.ts'
  
  @Controller('/home')
  export class HomeController {
    @Get('/text')
    text() {
      return Content("Hello world");
    }
    @Get('/json')
    json() {
      return Content({"text":"test"});
    }
  }
  @Area({
    controllers: [HomeController]
  })
  export class HomeArea {
  }
  const app = new App({
    areas: [HomeArea]
  });
  
  app.listen();

[error]

Compile file:///Users/liu/Desktop/deno/web/app.ts
error TS2339: Property 'DenoError' does not exist on type 'typeof Deno'.

► https://deno.land/std@v0.34.0/path/glob.ts:6:9

6 const { DenoError, ErrorKind } = Deno;
          ~~~~~~~~~

error TS2339: Property 'ErrorKind' does not exist on type 'typeof Deno'.

► https://deno.land/std@v0.34.0/path/glob.ts:6:20

6 const { DenoError, ErrorKind } = Deno;
                     ~~~~~~~~~

error TS2339: Property 'DenoError' does not exist on type 'typeof Deno'.

► https://deno.land/x/alosaur/src/static/send.ts:160:29

160     if (err instanceof Deno.DenoError) {
                                ~~~~~~~~~

error TS2339: Property 'ErrorKind' does not exist on type 'typeof Deno'.

► https://deno.land/x/alosaur/src/static/send.ts:161:29

161       if (err.kind === Deno.ErrorKind.NotFound) {
                                ~~~~~~~~~

Found 4 errors.

**Comment by Joshua-Rowe** [comment]
I had this same issue. I installed Deno via Homebrew originally, and I encountered the error when simply following the demo instructions. Currently the most recent version of Deno is 0.35 and Homebrew installs that version when running `brew install deno` , but you can see by the error that Alosaur uses std 0.34. After installing Deno using the command `curl -fsSL https://deno.land/x/install/install.sh | sh -s v0.34.0`, the demo worked as expected. Let me know if you can confirm.

**Comment by irustm** [comment]
@Joshua-Rowe thanks. I'll update Alosaur to deno 0.35

**Comment by irustm** [comment]
@liuxiaobina @Joshua-Rowe i updated Alosaur to Deno 0.35

open this issue if you have any questions.
