### ISSUE TITLE
upgrade deno to 1.6.0

### ISSUE THREAD

**Issue by Boyceman** [alosaur/alosaur#110]
hi, could i know when will you upgrade std to 0.79.0 please? deno has an important bug fixed in verison 1.5.4, and i need it. so, looking for your updating. thanks in advance😊
 [https://github.com/denoland/deno/issues/8107#issuecomment-729693047](https://github.com/denoland/deno/issues/8107#issuecomment-729693047)

**Comment by timonson** [comment]
I opened the quoted issue in the deno repo. Unfortunately the bug has not been fixed yet.

**Comment by Boyceman** [comment]
should i wait the latest release if i wanna use it? or maybe has any other way? could you help me out it? thanks so much.

**Comment by Boyceman** [comment]
cool, thanks!
