### ISSUE TITLE
Add ORM like Django

### ISSUE THREAD

**Issue by borisliu** [alosaur/alosaur#123]
I like Django's ORM.It is very easy to develop app using rational db.I also like syntax of spring ORM. Because the decorators make it more friendly.Do you have any plan to add the ORM to alosaur framework?

If you don't, how do you think I pull some code to the project?

Maybe I'll borrow some code from typeorm(https://github.com/denolib/typeorm) or mandarinets(https://github.com/mandarineorg/mandarinets)

**Comment by irustm** [comment]
ORM is not part of the Alosaur web framework. At this point, you can use any ORM you like. For example here is an article on how to use TypeOrm with Alosaur 

[Create a Deno Rest API: A promising start with Alosaur and TypeORM]
https://dev.to/hugoblanc/create-a-deno-rest-api-a-promising-start-with-alosaur-and-typeorm-n28
