### ISSUE TITLE
Can we add an example of uploading files?

### ISSUE THREAD

**Issue by vjeson** [alosaur/alosaur#125]
Can we add an example of uploading files？ It's really very a basic feathure.

**Comment by irustm** [comment]
Yes, that's exactly what I'm doing right now. I think there will be a new release today if all the tests pass. 

https://github.com/alosaur/alosaur/issues/119
https://github.com/alosaur/alosaur/issues/63

**Comment by irustm** [comment]
https://github.com/alosaur/alosaur/tree/master/examples/form-data
