### ISSUE TITLE
add swagger decorator like nestjs/swagger

### ISSUE THREAD

**Issue by AlfieriChou** [alosaur/alosaur#13]
https://github.com/nestjs/swagger

**Comment by irustm** [comment]
I am thinking of adding a generator according to this specification https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v3.0.

**Comment by irustm** [comment]
I added a generator to build the documentation, but so far without bindings by type.

Example in https://github.com/alosaur/alosaur/blob/master/examples/basic/openapi.ts

Generate openAPI file:

```
deno run -A --config ./src/tsconfig.lib.json examples/basic/openapi.ts

```
And this generate to file:

https://github.com/alosaur/alosaur/blob/master/examples/basic/api.json

**Comment by irustm** [comment]
Added type reference with JsDoc and Deno Doc parse:
 https://github.com/alosaur/alosaur#openapi-v3
