### ISSUE TITLE
Connecting to microservices

### ISSUE THREAD

**Issue by Jordan-Hall** [alosaur/alosaur#138]
Have you considered how to get microservices to connect to each other? I don't mind helping out  as it appears this is the last major thing missing from the amazing framework :)

**Comment by irustm** [comment]
I like the overall implementation as in https://docs.nestjs.com/microservices/basics

but maybe for Alosaur can do even better. So far I haven't dealt with this question

**Comment by irustm** [comment]
# Alosaur microservices

Will have: `Areas, Controlers, Hooks, DI containers`

## Server

Create and listen microservice

```ts

// Service with declare Area

const service = new Microservice({
    areas: [MicroserviceArea],
    transport: Transport.TCP,
    options: {
        port: 3500,
       ...
    }
})

service.listen();



@Controller()
export class MyServiceConroller{
    
    @Pattern("sum")
    sum(context: TcpContext) {
        
    }

    @Event("sumevent")
    sumevent(context: TcpContext) {

    }
}

```

## Client

Declare with provider factory, on App, Microservice, Area, Controller 

```ts
providers: [
    {
        token: "TCP_CLIENT",
        useFactory: () => {
            return new MsTcpClient({port: 3500})
        }
    }
]

/// Controller

@Controller('test')
class TestController {
  constructor(@Inject("TCP_CLIENT") client){}
  
  @Get()
  async get() {
     await this.client.dispatch({cmd: 'sum'});
  }
}

```

## Transports

- [ ] TCP (by default) - Deno.listen / Deno.connect
- [ ] Unix (files)
- [ ] gRPC
- [ ] Redis
- [ ] ...



## Alosaur CLI

For run multiply application and microservices use Alosaur CLI

## Third party

Official TCP connectors to Node.JS, Rust, .Net

**Comment by irustm** [comment]
Implemented TCP client and server by default,

https://github.com/alosaur/alosaur/pull/143


Docs:
https://github.com/alosaur/alosaur/tree/master/src/microservice
