### ISSUE TITLE
MIME support

### ISSUE THREAD

**Issue by x4m3** [alosaur/alosaur#20]
I'm using alosaur to serve a static css file.

However, Chromium would not accept my css file as a css file because of the mime during transfer (`text/plain` instead of `test/css`). screenshot attached.

![Screenshot from 2020-04-12 01-10-20](https://user-images.githubusercontent.com/8809909/79056822-92cc8800-7c5a-11ea-959a-fe2e7656c7a9.png)

Do you have an idea if this issue could be fixed or implemented? I looked around in the source code but could not find anything related to MIMEs. I'd be down to help though.

Thanks!

**Comment by irustm** [comment]
Thank you!

Fixed in v0.7.2

**Comment by x4m3** [comment]
works like a charm! thx!
