### ISSUE TITLE
No export named DenoDoc after Deno v1.38.0

### ISSUE THREAD

**Issue by SeanWong24** [alosaur/alosaur#202]
After upgrading to Deno v1.38.0, I got the following error when using the OpenAPI builder, which does not seem to happen in Deno v1.37

```
error: Uncaught SyntaxError: The requested module './deno-doc.model.ts' does not provide an export named 'DenoDoc'
import { DenoDoc } from "./deno-doc.model.ts";
         ^
    at <anonymous> (file:///workspaces/alosaur/openapi/parser/src/js-doc-parser.ts:1:10)
```

This should be able to reproduce by running `/openapi/e2e/openapi-builder.ts` in this repository.

**Comment by irustm** [comment]
solved in v1.0.0
