### ISSUE TITLE
Up to ES decorators after Deno 1.40

### ISSUE THREAD

**Issue by irustm** [alosaur/alosaur#203]
https://deno.com/blog/v1.39#upcoming-changes-to-the-decorators

**Comment by ball6847** [comment]
Apart from es decorators change, `Deno.serveHttp` should be replaced with `Deno.serve` as  `Deno.serveHttp` is deprecated now. 

https://deno.com/blog/v1.40#deprecations

**Comment by irustm** [comment]
+

https://github.com/tc39/proposal-class-method-parameter-decorators

**Comment by af280cf94190a54043e947948a0031ce7ed71dc** [comment]
Why method decorators over parameter decorators in latest release?

**Comment by irustm** [comment]
> Why method decorators over parameter decorators in latest release?

Because they're not in ES Decorators yet.
They were only available in Typescript.
Expect them to be added to javascript someday https://github.com/tc39/proposal-class-method-parameter-decorators

**Comment by e991f665b7e62df5a54fdef19053a4e75117b89** [comment]
> > Why method decorators over parameter decorators in latest release?
> 
> Because they're not in ES Decorators yet. They were only available in Typescript. Expect them to be added to javascript someday https://github.com/tc39/proposal-class-method-parameter-decorators

Okay, but as they are supported in Deno, why were they removed? Imo, I believe they were a really useful addition, and on of the main reasons Alosaur was so appealing to me.

Do you have any plans to add support back to Alosaur for them?

**Comment by irustm** [comment]
Another problem is that typescript 5.0 no longer supports reflect-metadata. 
I think this downgrade will be hard to support.
I also think that Deno will remove experimental decorators in the near future. https://github.com/denoland/deno/issues/19160 
Just like in typescript itself.

I tried to keep the approximate API as much as possible with @ActionParam

```diff 
@Controller("/home")
export class HomeController {
   @Get("/query-name")
+  @ActionParam(0, QueryParam("name"))
+  text(name: string) {
-  text(@QueryParam("name") name: string) {
    return Content(`Hey! ${name}`);
  }
}
