### ISSUE TITLE
baseRoute for useStatic

### ISSUE THREAD

**Issue by pgg** [alosaur/alosaur#24]
assuming my angular app is in the ./app folder, the only way i can get it to work is with:
```
app.useStatic({
  root: `${Deno.cwd()}/app`,
  index: 'index.html'
});
app.listen();
```
and in index.html ```<base href="/" />```, then get on 0.0.0.0:8000 renders the angular app default route i.e: 0.0.0.0:8000/info

how do I get it to work as ```<base href="/app/" />```? I would assume like this:
```
app.useStatic({
  root: `${Deno.cwd()}/app`,
  index: 'index.html',
  baseRoute: '/app/'
});
app.listen();
```
but it does not seem to work, or am I doing something wrong?

**Comment by irustm** [comment]
I think, you can write middlware for this actions, or we can create app.useSpa in alosaur, 
for example: 
in .NetCore [usespa](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.spaapplicationbuilderextensions.usespa?view=aspnetcore-3.0)

**Comment by pgg** [comment]
> I think, you can write middlware for this actions, or we can create app.useSpa in alosaur,
> for example:
> in .NetCore [usespa](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.spaapplicationbuilderextensions.usespa?view=aspnetcore-3.0)

think useSpa is a good idea

**Comment by irustm** [comment]
Added spa example
https://github.com/alosaur/alosaur/tree/master/examples/spa

**Comment by pgg** [comment]
> Added spa example
> https://github.com/alosaur/alosaur/tree/master/examples/spa

awesome
