### ISSUE TITLE
suggestion: using `deno fmt` to format code

### ISSUE THREAD

**Issue by x4m3** [alosaur/alosaur#30]
deno includes a code formatter by default with the command `deno fmt`.

maybe the code could be formatted to have consistency across the project and have future pull requests require it in order to keep that consistency?

**Comment by irustm** [comment]
Yeah, I thought about it, but I haven't gotten to it yet.

**Comment by irustm** [comment]
I'll be waiting https://github.com/denoland/deno_lint

**Comment by irustm** [comment]
done!
