### ISSUE TITLE
how to set cookies

### ISSUE THREAD

**Issue by x4m3** [alosaur/alosaur#31]
I see there is a way to retrieve cookies via the Cookie decorator (`@Cookie('login') login: string` as an exemple), but I didn't find the code a way to set cookies.

I saw in https://deno.land/std/http/cookie.ts that there is a function to set cookies, maybe add in the framework a way to set cookies?

**Comment by SeanWong24** [comment]
Agree, it would be great to have a convient way to set and delete a cookie.

Currently I could set cookies by using code like
```ts
async setACookie(@Res() response: Response) {
    setCookie(response, { name: "someCookie", value: "someValue", path: "/" });
    return response;
  }
```
and delete a cookie by 
```ts
async deleteACookie(@Res() response: Response) {
    delCookie(response, "someCookie");
    return response;
  }
```
In the code sample ```setCookie()``` and ```delCookie()``` are imported from ```"https://deno.land/std/http/cookie.ts"```.

But I realized that I can only make it work by using ```return response;``` and did not figure out how to make it work by using ```return Content(jsonToReturn);```.

**Comment by x4m3** [comment]
> But I realized that I can only make it work by using return response; and did not figure out how to make it work by using return Content(jsonToReturn);.

yup, i've got the same issue! here's how i implemented to store a cookie and render some ejs:

```typescript
let response = await View("pages/ok", {});
setCookie(response, { name: "someCookie", value: someValue });

return response;
```

**Comment by SeanWong24** [comment]
I think currently to manually set the response is possible but a more convient way to set a cookie is still fairly helpful.

It could be nice if we can handle cookies using the way similar to asp.net core.
```cs
Request.Cookies[Key]; 
Response.Cookies.Append(key, value, option); 
Response.Cookies.Delete(key);
```

**Comment by irustm** [comment]
@SeanWong24 
Yeah, that's a good idea, I'll get to it soon.

**Comment by irustm** [comment]
Now, after #33.

You can write

```ts
  @Get('/view')
  view(@Res() response: Response ) {
    setCookie(response, { name: "someCookie", value: someValue });
    return View(result);
  }
