### ISSUE TITLE
simplify the return behavior

### ISSUE THREAD

**Issue by SeanWong24** [alosaur/alosaur#33]
Does it make sense to use Content() function to process the return value by default if the return value is not a response object?

For example, when I write a method in a controller, 
if I just return a number, boolean, string, object, or list, the framework automatically apply Content() function to make it a response;
if I return a customized response object (also includes the object processed by View() function), then there is no need to be processed by the Content() function again;
If I do not return anything, then the response body should be empty.

Also, for #31 , if the response is modified (such as adding headers), it should always be applied whatever I returned from the method in the controller.

**Comment by irustm** [comment]
I think it's only worth doing on default for `Content()`.
Because `Redirect('/route')`(#34) , `View` and others necessary utilities functions

**Comment by SeanWong24** [comment]
I guess my explaination is not clear enough. Basically, what I was trying to say is to make it behaves like in asp.net core. When we want to return a content result, we do not need to call Content() before return. For those utility function, they should not be affected.

**Comment by irustm** [comment]
Added Content by default and headers merge.

```ts
  @Get('/query')
  query(@QueryParam("a") a: string, @QueryParam("b") b: string, @QueryParam("c") c: string) {
    return { a, b, c };
  }

  @Get('/test')
  gerTests() {
    return 'test';
  }
  
  @Get('/test/:id')
  gerParamId(@Param('id') id: string) {
    return id;
  }

  @Get('/test/:id/:name')
  gerParamIdName(@Param('id') id: string, @Param('name') name: string) {
    return `${id} ${name}`;
  }
```
