### ISSUE TITLE
redirect to url inside a controller

### ISSUE THREAD

**Issue by x4m3** [alosaur/alosaur#34]
inside a controller, is there a way to redirect to a specific url instead of returning some content (View, Text, Json, etc) ?

I'm looking for something like this:

```typescript
@Post("")
async loginRequest(@Cookie('autologin') CookieAutologin: string) {

    if (CookieAutologin !== undefined) {
      // redirect to "/"
    }

    // [...] rest of controller
}
```

thanks

**Comment by irustm** [comment]
Thanks! 
Added 
`Redirect('/path/')` and `RedirectPermanent('/path/')`
