### ISSUE TITLE
up to Deno v0.42.0

### ISSUE THREAD

**Issue by SeanWong24** [alosaur/alosaur#39]
It seems there are some breaking changes of Deno v0.42.0, which make the framework fail to run.

**Comment by irustm** [comment]
Yeah, I'll update today.

**Comment by irustm** [comment]
For update
need update dependecy `dejs` https://github.com/syumai/dejs
and 

https://github.com/alosaur/alosaur/tree/deno_v042

**Comment by irustm** [comment]
https://github.com/alosaur/alosaur/releases/tag/v0.12.0
