### ISSUE TITLE
How to know which API is called in middleware?

### ISSUE THREAD

**Issue by SeanWong24** [alosaur/alosaur#42]
Just checked the log middleware example in readme, which only logs the time. I am wondering how I could obtain which API is called when implementing a middleware. For example, can I get the method name of the API handling method?

**Comment by irustm** [comment]
Give me an example of what this might be for?

Now you can take the url from the request.

**Comment by SeanWong24** [comment]
Thanks, I did not check the request object carefully and getting the url should work for me now. I was just tried to log which and when an API was called.
