### ISSUE TITLE
Correct use of @Injectable()

### ISSUE THREAD

**Issue by omirobarcelo** [alosaur/alosaur#47]
In the DB example, the [user.service](https://github.com/alosaur/alosaur/blob/master/examples/db/services/user.service.ts) uses `@Injectable()`.

In the DI example, the [foo.service](https://github.com/alosaur/alosaur/blob/master/examples/di/services/foo.service.ts) does not use it. 

But in both cases the services are injected in the controller that makes use of them. 
Is the DB example using `@Injectable()` for the database?  
What is the correct use of `@Injectable()`, and other related decorators like `@Singleton()`?

**Comment by irustm** [comment]
UserService uses other not resolved Database,
and to say that it should create and implement the Database service you need to use Injectable() decorator in UserService

FooService and UserService injected in controllers. Controllers = Injectable by default

Full documentation about Alosaur injection
https://github.com/alosaur/alosaur/tree/master/src/injection
