### ISSUE TITLE
Why is @Area decorator named this way

### ISSUE THREAD

**Issue by vblazenka** [alosaur/alosaur#48]
Hi, good work on the framework. I'm excited to play with it.

I just wanted to raise my concern of naming decorator @Area the way it is named.

Why it isn't named @Module? It would be more straightforward and it would help with the consistency in the community instead of inventing new namings.  

Inspiration: https://docs.nestjs.com/modules

**Comment by SeanWong24** [comment]
Seems this has already been answered.
#7

**Comment by irustm** [comment]
In NestJs, the modules are very similar to Angular. In Angular, it's also made to resolve `providers`.

In Alosaur, you can't embed in Area in Area. 

In Alosaur control over DI, you can do it manually and build your system with TSyringe.

I'm gonna put that in a separate place in the documentation.
