### ISSUE TITLE
Templating Engine?

### ISSUE THREAD

**Issue by MegaITA** [alosaur/alosaur#49]
Hi, I'm approaching to deno and this library. I'm curious to know if there's any templating engine (like handlebars) in order to pass variables to the web view. It would be nice.

**Comment by irustm** [comment]
Hi, this is a possibility!

You can see as an example `dejs`:
https://github.com/alosaur/alosaur/tree/master/examples/dejs

I also ported `handlebars`:
https://github.com/alosaur/handlebars
