### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by irustm** [alosaur/alosaur#5]

**Comment by muuvmuuv** [comment]
Compare with NestJS for example. Good starting point is this repo, maybe be can port it over to Deno and add more frameworks from Deno and NodeJS for comparison:

https://github.com/fastify/benchmarks

**Comment by muuvmuuv** [comment]
Good article about comparing Deno Web/Api Frameworks: https://dev.to/craigmorten/what-is-the-best-deno-web-framework-2k69

**Comment by irustm** [comment]
Following this article, I ran tests on my MacBook 13, 2 GHz Intel Core i5, 8 ГБ 1867 MHz LPDDR3

Node v13.5.0, @nestjs/core 7.1.3
Avg RPS: **11651**

Deno v1.1.0, Alosaur v0.19.3
Avg RPS: **24827**
