### ISSUE TITLE
Response Status Code

### ISSUE THREAD

**Issue by truefalse10** [alosaur/alosaur#50]
Is there a way to set the response status code? Currently I am automatically getting a 200 but it would be nice to be able to set it manually

**Comment by irustm** [comment]
There are 3 ways of information output

https://github.com/alosaur/alosaur/tree/master/src/renderer

- **Content** similar `return {};` by default Status 200 OK
- **View** with template engine, `return View("index", model)`;
- **Redirect** and **RedirectPermanent** status 301,302 `return Redirect('/to/page')`

And status is also supported for 2 output

```ts
// action
...
return Content("Text or Model", 404); // return 404 status

// or 
return View("page", 404); // return 404 status

```
