### ISSUE TITLE
How to catch the errors from the middleware?

### ISSUE THREAD

**Issue by SeanWong24** [alosaur/alosaur#51]
I am just wondering how I should know if there is an error thrown in the controller when I implement a middleware.

**Comment by irustm** [comment]
In the current implementation, you can write the information into the object of response. 
But if it doesn't suit you, please describe in full what you want to do

```ts
//  implements MiddlewareTarget

onPreRequest(request: ServerRequest, response: ServerResponse): Promise<void> {
  // write to responce. -?
}
```

**Comment by SeanWong24** [comment]
I wanted to implement a log middleware that applies to all controllers and I was able to log the url, time, query parameters, etc. But I also want to know if the request is successful or failed, and if it is failed, I also want to know the error information.

**Comment by irustm** [comment]
there'll be another decorator for these things soon.

Hooks - middlware for actions
```ts

@Controller()
@Hooks(MyActionHooks) // for all actions of controller
export class HomeController {

   @Get('/')
   @Hooks(MyActionHooks) // or for one action
   get() { .... }
}
```
action.hooks.ts

```ts
export class MyActionHooks implements ActionHooks {

   onPreAction(request, response): ServerResponse { 
     // 
     return response;
   }

   onPostAction(request, response): ServerResponse { 
     // 
     return response;
   }

   onCatchAction(request, response, error): ServerResponse { 
     // 
     return response;
   }
   
}

```

it'll help make authorization, etc.

I'll be glad to hear another opinion =)

**Comment by irustm** [comment]
and it's possible that onCatch will also be implemented in standard middlware.

**Comment by SeanWong24** [comment]
It looks awesome. Just one thought, would that make sense to make Hooks() also receive an optional options parameter then we can handle different actions slightly different with the same hook implementation.

**Comment by irustm** [comment]
I think it might be possible to do this 

```ts
export class MyActionHooks implements ActionHooks {
  static configure(options): MyActionHooks {
       return new MyActionHooks(oprtions);
  }
  constructor(private options) {
}
}

```
then:

```ts

@Hooks(MyActionHooks.configure({option}));

// or create global class instance

const myHook = MyActionHooks.configure({});


@Hooks(myHook)
...
```

**Comment by irustm** [comment]
The next release will be a Context wrapper.

`context.response.error`

In the middlware will be available DI container.

an example with hooks is available here:

https://github.com/alosaur/alosaur/tree/master/examples/hooks

**Comment by irustm** [comment]
https://github.com/alosaur/alosaur/releases/tag/v0.15.0

**Comment by omirobarcelo** [comment]
I'm looking to do what @SeanWong24 wrote:
> I wanted to implement a log middleware that applies to all controllers and I was able to log the url, time, query parameters, etc. But I also want to know if the request is successful or failed, and if it is failed, I also want to know the error information.

I understand that now with hooks we could get the response status (200, 401, 404...), but can we get it in a Middleware? `context.state` returns `undefined` in `onPostRequest`. 

If not, can we apply a hook to the whole application?

**Comment by SeanWong24** [comment]
> If not, can we apply a hook to the whole application?
I think now the Hooks can be applied to areas, maybe you can try that?

**Comment by irustm** [comment]
you can now apply hooks to the area and gets status from `context.response.result` - ActionResult

**Comment by omirobarcelo** [comment]
For my current project I only have one Area, so it would work, but ideally I wanted it to be App level.

I ended up doing this on my Log middleware:
```
  onPostRequest(context: Context<unknown>) {
    return new Promise((resolve, reject) => {
      const printMethod = `${yellow('[')}${white(context.request.method)}${yellow(']')}`;
      const status = context.response.error ? (context.response.error as HttpError).httpCode || 500 : (context.response.status ? context.response.status : 200);
      const printStatus = cyan(status.toString(10));
      const httpVersion = cyan(context.request.serverRequest.proto);
      const localAddr = context.request.serverRequest.conn.localAddr as any;
      const ip = cyan(`${localAddr?.hostname}:${localAddr?.port}`);
      const endpoint = `[${white('route:')} ${blue(context.request.url)}]`;
      Logger.log(
        `${printMethod} ${printStatus} ${white('|')} ${httpVersion} ${white('|')} ${ip} ${endpoint}`
      );
      resolve();
    });
  }
```

It works for my purposes.

Thanks for the suggestions!
