### ISSUE TITLE
Getting error after updating to Deno v1.0.1

### ISSUE THREAD

**Issue by SeanWong24** [alosaur/alosaur#55]
After I updating to Deno v1.0.1 and trying to run an Alosaur project that previously works, I just got an error with no detailed error message.

**Comment by irustm** [comment]
Yeah, got the same in 1.0.1.

It's now upgraded to Deno 1.0.2, and it's working.

Try upgrade to Deno 1.0.2

**Comment by SeanWong24** [comment]
Thanks, it works after upgrade to Deno 1.0.2. Closing the issue.
