### ISSUE TITLE
CORS doesn't work correctly on dockerized app

### ISSUE THREAD

**Issue by omirobarcelo** [alosaur/alosaur#57]
I have a simple app as such:
```
const app = new App({
  areas: [GraphDBArea, HomeArea],
  middlewares: [Log]
});

app.useCors(
  new CorsBuilder()
    .AllowAnyOrigin()
    .AllowAnyMethod()
    .WithHeaders(['Origin', 'X-Requested-With', 'Authorization', 'Content-Type', 'Accept'].join(','))
);

app.listen();
```

I am using a Svelte frontend that uses the standard Fetch API to query the backend:
```
  const url = 'http://localhost:8000/graph-db';
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });
  return response.json();
```

When I run locally the backend using Deno, I can query the backend both using the browser directly or through a Fetch request using the Svelte frontend.

I dockerized the backend application with the following Dockerfile:
```
FROM hayd/alpine-deno:1.0.0

# The port that your application listens to.
EXPOSE 8000

WORKDIR /app

# Prefer not to run as root.
USER deno

# Cache the dependencies as a layer (the following two steps are re-run only when deps.ts is modified).
# Ideally cache deps.ts will download and compile _all_ external files used in main.ts.
COPY deps.ts .
RUN deno cache deps.ts

# These steps will be re-run upon each file change in your working directory:
ADD . .
# Compile the main app so that it doesn't need to be compiled each startup/entry.
RUN deno cache -c tsconfig.json app/app.ts

CMD ["run", "--allow-net", "-c", "tsconfig.json", "app/app.ts"]
```

When I query the backend using the browser directly it works, but when using the Svelte frontend, the `Access-Control-Allow-Origin` header is not set, blocking the response.

Is it a configuration error on my side? Is the Dockerfile incorrect? Is it a bug?

**Comment by irustm** [comment]
Does your application send a header `Origin`?

**Comment by omirobarcelo** [comment]
Seems the problem is connecting from a dockerized Alosaur app to a dockerized database. 

My controller was executing something like this:
```
const sparqlFunction = async (q: string) =>
    (await soxa.get(`http://localhost:7200/repositories/instance001`, { params: { query: q } })).data;
return sparqlTransformer(query, { sparqlFunction, debug: true });
```
Where `localhost:7200` is a dockerized database. 

Closing the issue because I assume this is not an Alosaur problem.
