### ISSUE TITLE
How to throw a ForbiddenError inside onPreAction of a Hook?

### ISSUE THREAD

**Issue by SeanWong24** [alosaur/alosaur#64]
In an action, we can just throw the error in the method. However, if I just throw an error in onPreAction method, it ends the app. I also tried to use ```context.response.result = Content(error, error.httpCode || 500);```, but it seems doing nothing inside onPreAction.
Another question is that, if the code inside onPreAction is async, it seems the app throws the error after responsing the request. How could I make sure the async code inside onPreAction is executed before responding the request?

**Comment by irustm** [comment]
You shouldn't throw errors inside hooks. But I can suppose that it can occur in third-party code. If there is such a need, you should control it yourself. For example, like this;

```ts
try {
// your code
} catch (error) {
   context.response.result = Content(error, error.httpCode || 500);
   context.response.setImmediately(); // move ahead immediately
}
```


async hooks fixed in v0.16.2
example with delay: [examples/hooks/hooks/async-pre-hook.ts](https://github.com/alosaur/alosaur/blob/master/examples/hooks/hooks/async-pre-hook.ts)

**Comment by SeanWong24** [comment]
Thanks, It works. Just wondering if it is an expected behaviour that the request would no longer be passed to ```onPostAction``` or ```onCatchAction``` when using ```setImmediately()``` .
My new problem is that I have used both ```onPostAction``` and ```onCatchAction``` to implement a log hook, but after I responding an ForbiddenError in ```onPreAction``` and using ```setImmediately()``` of an authorization hook, the log hook for that action no longer works.

**Comment by irustm** [comment]
Yes, this could be a problem now.

I think it should be done in such a way that the upper hooks should be run anyway...

```
AreaHook - calls onPreAction
   ControllersHooks - calls onPreAction
       ActionHooks  - calls onPreAction and one of hooks `setImmediately()`
           ActionResult - not calls 
       ActionHooks - not calls onPostAction
    ControllersHooks - calls onPostAction
AreaHook  - calls onPostAction
```

onCatchAction is called only if it is in ActionResult.

**Comment by SeanWong24** [comment]
No sure if I understand, does that mean, if I want ```onPostAction``` to be called, the log hook has to be set to a controller or area instead of an action?

**Comment by irustm** [comment]
Which means it has to be declared higher than setImmediately.

```
ActionHooks1 - calls onPreAction 
ActionHooks2 - calls onPreAction and one of hooks `setImmediately()`
       ActionResult - not calls 
ActionHooks2 - not calls onPostAction
ActionHooks1 - calls onPostAction
```

this has not yet been implemented now but will be done in the next version.
