### ISSUE TITLE
Cannot get body in hooks

### ISSUE THREAD

**Issue by SeanWong24** [alosaur/alosaur#65]
I tried to use the code below to get body string of a request inside ```onPostAction``` method of a hook, but even though ```context.request.serverRequest.contentLength``` is greater than 0, the body string is always ```""```.
```ts
let body = await Deno.readAll(context.request.serverRequest.body);
const bodyString = new TextDecoder("utf-8").decode(body);
```

**Comment by irustm** [comment]
To test this, I specifically created an example https://github.com/alosaur/alosaur/blob/master/examples/hooks/hooks/post-hook.ts

and sent a `POST` request 

```
curl -X POST \
  http://localhost:8000/post-hook \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
	"title": "First post",
	"text": "hello!",
	"rating": 5,
	"email": "aa@mail.com"
}'
```
it works.

**Comment by SeanWong24** [comment]
I realized that this would only happen when the body is read before. For example, the action handler uses ```@Body```, and then in the hook, it reads nothing. To make sure my guess, I have tried to remove the ```@Body``` in the action handler and use code like this below, and it read something for the first time but nothing for the second time.
```ts
let body = await Deno.readAll(context.request.serverRequest.body);
body = await Deno.readAll(context.request.serverRequest.body);
```

Not sure if this is a bug of Deno or Alosaur, maybe update Deno std version used by Alosaur could be a solution?

**Comment by irustm** [comment]
I just checked. It's not really working.

```ts
import { serve } from "https://deno.land/std@0.54.0/http/server.ts";

for await (const req of serve({ port: 8000 })) {
    let body = await Deno.readAll(req.body);
    body = await Deno.readAll(req.body);
    const bodyString = new TextDecoder("utf-8").decode(body);
    req.respond({ body: bodyString });
}
```

**Comment by irustm** [comment]
In that case, I'll make it possible to get the body from `context.request.body`.

**Comment by irustm** [comment]
await context.request.body() 
from Alosaur v0.17.0
