### ISSUE TITLE
Uncaught TypeError: Cannot resolve extension for "https://raw.githubusercontent.com/jshttp/mime-db/master/db.json" with mediaType "Json".

### ISSUE THREAD

**Issue by borisliu** [alosaur/alosaur#69]
I run the sample in my Win10 computer.But there always show the error:

Uncaught TypeError: Cannot resolve extension for "https://raw.githubusercontent.com/jshttp/mime-db/master/db.json" with mediaType "Json".

Does anyone know how to fix the problem?

**Comment by irustm** [comment]
Please let me know what code you are trying to run and what version of Deno and Alosaur you have.

**Comment by borisliu** [comment]
My Code is

**app.ts**
```
import { Controller, Get, Area, App } from 'https://deno.land/x/alosaur/mod.ts';

@Controller('/home')
export class HomeController {
    @Get('/text')
    text() {
        return 'Hello world';
    }
    @Get('/json')
    json() {
        return { text: 'test' };
    }
}

// Declare module
@Area({
    controllers: [HomeController],
})
export class HomeArea {}

// Create alosaur application
const app = new App({
    areas: [HomeArea],
});

app.listen();
```

**tsconfig.app.json**
```
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    }
}
```

**shell command**
```
deno run --allow-net --allow-read --config ./tsconfig.app.json app.ts
```

**development envionment**
```
deno 1.0.5
v8 8.4.300
typescript 3.9.2
```

**os version**
```
Microsoft Windows [版本 10.0.18363.836]
(c) 2019 Microsoft Corporation。保留所有权利。
```

**Comment by irustm** [comment]
I've updated deps, try use Alosaur v0.18.1 
https://deno.land/x/alosaur@v0.18.1/mod.ts

**Comment by thereis** [comment]
I'm still having the same trouble. I've tried to run the example code from the documentation, but I was not able to reach any created route even with your latest release.

**Comment by borisliu** [comment]
It works!
Thanks a lot.

**Comment by borisliu** [comment]
Please let me know what code you are trying to run and what version of Deno and Alosaur you have.


发送自 Windows 10 版邮件应用

发件人: Lucas Reis
发送时间: 2020年6月9日 9:18
收件人: alosaur/alosaur
抄送: Boris Liu; Author
主题: Re: [alosaur/alosaur] Uncaught TypeError: Cannot resolve extensionfor "https://raw.githubusercontent.com/jshttp/mime-db/master/db.json" withmediaType "Json". (#69)

I'm still having the same trouble. I've tried to run the example code from the documentation, but I was not able to reach any created route even with your latest release.

**Comment by thereis** [comment]
> Please let me know what code you are trying to run and what version of Deno and Alosaur you have. 发送自 Windows 10 版邮件应用 发件人: Lucas Reis 发送时间: 2020年6月9日 9:18 收件人: alosaur/alosaur 抄送: Boris Liu; Author 主题: Re: [alosaur/alosaur] Uncaught TypeError: Cannot resolve extensionfor "https://raw.githubusercontent.com/jshttp/mime-db/master/db.json" withmediaType "Json". (#69) I'm still having the same trouble. I've tried to run the example code from the documentation, but I was not able to reach any created route even with your latest release. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

It's working incredibly well! Loved the similarity to the NestJS framework. You can close the issue if you want.
