### ISSUE TITLE
Ipv6 support

### ISSUE THREAD

**Issue by loic-roux-404** [alosaur/alosaur#71]
Hello,
first your framework is very good, congrats !

In a second part i wan't to know if it's possible to allow passing an HttpOption Object to function like 
```ts
app.listen({
   port: 8000,
   hostname: [::1] // Ipv6 wich broke app by passing full address in function
})
```

I't will be a pleasure to submit a PR if you want to !

**Comment by irustm** [comment]
Thanks! 
Yeah, I'd welcome any PR

**Comment by irustm** [comment]
#75
