### ISSUE TITLE
Delete method don't handle params in async context

### ISSUE THREAD

**Issue by loic-roux-404** [alosaur/alosaur#76]
When method is async get not handle params in url

 ```ts
 @Delete("/delete/:id")
  async delete(@Param("id") id: number) {
    console.log(id); // throw "Cannot read property 'id' of undefined"
```

**Comment by irustm** [comment]
not to reproduce https://github.com/alosaur/alosaur/blob/master/examples/basic/areas/home/home.controller.ts#L66

Need more information

**Comment by loic-roux-404** [comment]
my Bad, work after `deno run --reload option`.
