### ISSUE TITLE
Add CLI schematics

### ISSUE THREAD

**Issue by irustm** [alosaur/alosaur#8]
Schematics:
- Create module/area
- Create service
- Create controller
...

**Comment by emjimadhu** [comment]
@irustm i think i can help you with creating schematics

**Comment by irustm** [comment]
Thank you! I'll be happy to have any PR.

**Comment by emjimadhu** [comment]
@irustm i have already created a private repo for the schematics in my personal account. If you could gimme your email, i can give access to my repo.

So far what is working on my schematics, you can generate app boilerplate with different ypes as you have `examples`

**Comment by irustm** [comment]
@emjimadhu jamakrus [at] gmail com

**Comment by emjimadhu** [comment]
@irustm I could not find you using that email. But anyways i have invited you using your username.

**Comment by irustm** [comment]
@emjimadhu 
Thank you! I got an invitation.
