### ISSUE TITLE
Is there any plan to implement passport strategy in alosaur?

### ISSUE THREAD

**Issue by eestevez** [alosaur/alosaur#80]
Is there any plan to implement passport strategy in alosaur as in https://github.com/nestjs/passport ? BTW good job doing and maintaining this project!

**Comment by irustm** [comment]
It's a good idea, but the trouble is, it's only about express. In NestJs, a passport can only work with express. I think we should transfer the passportjs code to Deno, and type it. Anyway, I'll consider different options.

**Comment by Jordan-Hall** [comment]
@irustm maybe use this https://github.com/oslabs-beta/onyx

**Comment by irustm** [comment]
@Jordan-Hall  Thank you! Looks interesting, I'll consider the possibilities of integration

**Comment by irustm** [comment]
I looked at it, onyx is heavily tied to oak, like passportjs to express, and onyx describes only one strategy for authorization. Unfortunately, this solution is not quite suitable for alosaur.

I think it is necessary to find a solution that would allow to use already existing strategies in passportjs.

**Comment by Jordan-Hall** [comment]
No problem. wasn't sure if the core could be used. I'm looking into auth this week with alosaur, I'll see what I can I find as it would be handy to port existing strategies

**Comment by fbaldo31** [comment]
There is maybe an alternative there [dashport](https://deno.land/x/dashport)
Looks like Passport for Deno :smiley:

**Comment by irustm** [comment]
dashport is heavily tied to oak, and has an OakContext link

**Comment by irustm** [comment]
Implemented
Docs: https://github.com/alosaur/alosaur/tree/master/src/security/oauth
