### ISSUE TITLE
deno 1.2.0 compatability

### ISSUE THREAD

**Issue by pgg** [alosaur/alosaur#81]
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.57.0/path/win32.ts:917:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.57.0/path/posix.ts:438:18

**Comment by irustm** [comment]
Thanks! fixed in Alosaur v0.21.0
