### ISSUE TITLE
spa-builder

### ISSUE THREAD

**Issue by pgg** [alosaur/alosaur#82]
config:

```
app.use(
  /\/www/,
  new SpaBuilder({
    root: `${Deno.cwd()}/www`,
    index: 'index.html',
    baseRoute: '/www/',
  })
);
```

angular app with base href ```/www/``` and default route ```/info``` renders and routes correctly, but if I hit browser refresh or paste the full url ```http://localhost:1447/www/info```:

```
Error: No such file or directory (os error 2)
    at send (send.ts:163:13)
    at async getStaticFile (get-static-file.ts:27:22)
    at async spa-builder.ts:12:11
```

app still works fine, but should this happen since it is not a static file, but an angular route . . .?

**Comment by irustm** [comment]
Thanks! fixed
