### ISSUE TITLE
middleware regex fails for trailing slash request

### ISSUE THREAD

**Issue by pgg** [alosaur/alosaur#83]
```
@Middleware(/^.*$/)
```
matches ```/ ``` and ```/path``` but does not match ```/path/```

**Comment by irustm** [comment]
Need more info.

it's not reproduced in this case
https://github.com/alosaur/alosaur/blob/master/examples/basic/middlewares/log.middleware.ts

**Comment by pgg** [comment]
this happens on the configured spa static path where ```/path``` is the angular app, so ```/path``` is logged but ```/path/``` is not

**Comment by pgg** [comment]
so this logs: ```http://localhost:1447/path``` but this does not ```http://localhost:1447/path/``` for both ```@Middleware(/^.*$/)``` and ```new RegEx("/")```

**Comment by irustm** [comment]
please give the minimum code where it happens, in the example everything works and works for each route

https://github.com/alosaur/alosaur/blob/master/examples/basic/middlewares/log.middleware.ts

**Comment by pgg** [comment]
GET on ```http://localhost:1448/www``` logs ```INFO /www``` but GET on ```http://localhost:1448/www/```
``` does not log
import * as alosaur from "https://deno.land/x/alosaur@v0.21.1/mod.ts";
import * as log from "https://deno.land/std@0.61.0/log/mod.ts";
import * as path from "https://deno.land/std@0.61.0/path/mod.ts";

// @alosaur.Middleware(/^\/.*$/)
 @alosaur.Middleware(/^.*$/)
//@alosaur.Middleware(new RegExp("/"))
class LogMiddleware implements alosaur.MiddlewareTarget<unknown> {
  onPreRequest(context: alosaur.Context<unknown>) {
    return Promise.resolve();
  }

  onPostRequest(context: alosaur.Context<unknown>) {
    return new Promise((resolve) => {
      log.info(() => `${context.request.url}`);
      resolve();
    });
  }
}

const app = new alosaur.App({
  areas: [],
  middlewares: [LogMiddleware],
});
app.use(
  new RegExp("/www"),
  new alosaur.SpaBuilder({
    root: `${path.dirname(path.fromFileUrl(import.meta.url))}/www`,
    index: "index.html",
    baseRoute: "/www/",
  }),
);
app.listen("localhost:1448");

```

**Comment by irustm** [comment]
Thanks! fixed on next release
