### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by pgg** [alosaur/alosaur#85]
is it possible to expose versioning info? Something like ```Deno.version``` for alosaur . . .

**Comment by irustm** [comment]
First of all, you have to go to the url with the version, it will eliminate many errors

`import { Controller, Get, Area, App } from 'https://deno.land/x/alosaur`**@v0.21.1**`/mod.ts';`

but I think someone can go directly to the master 
Which will not be stable and may not match the current version.

**Comment by pgg** [comment]
looking for some form of runtime inspection . . .

**Comment by irustm** [comment]
import { VERSION } from 'https://deno.land/x/alosaur/mod.ts';
