### ISSUE TITLE
mod.ts doesnt have Area as exported member?

### ISSUE THREAD

**Issue by emjimadhu** [alosaur/alosaur#87]
For some reasons every import i do it is giving there is no exported member?

![Screenshot from 2020-09-01 04-29-54](https://user-images.githubusercontent.com/15604962/91777207-dbd2a800-ec0c-11ea-8ddf-8baefb0ebd01.png)

So i observed that almost all the classes are giving the error. So i have importmap.

**Comment by irustm** [comment]
You should import from this url:
`import { Controller, Get, Area, App } from 'https://deno.land/x/alosaur@v0.21.1/mod.ts';`

without `/src/`

**Comment by emjimadhu** [comment]
@irustm Thanks it works. But i think there is an issue with angular example.

![Screenshot from 2020-09-09 09-40-22](https://user-images.githubusercontent.com/15604962/92553528-bf73e280-f280-11ea-842a-9fb7343da86a.png)

**Comment by irustm** [comment]
Thanks! fixed in alosaur deps
