### ISSUE TITLE
How to test using library like superdeno?

### ISSUE THREAD

**Issue by DanielRamosAcosta** [alosaur/alosaur#93]
I would like to test the API with a DSL like [superdeno](https://github.com/asos-craigmorten/superdeno), is this possible?

Thanks!

**Comment by irustm** [comment]
it looks like superdeno is just a wrapper to do http requests + tests. so there are no restrictions on its use.

Alosaur has its own utilities for this, you can see it in the 
https://github.com/alosaur/alosaur/tree/master/e2e
