### ISSUE TITLE
Create commands to initiate basic project

### ISSUE THREAD

**Issue by samchar** [alosaur/alosaur#94]
Drash gave tools to users to create base project with folder structure. 

https://nest.land/package/deno-drash

You guys already have example projects in the repo, I'm wondering if you would consider implementing such feature, as well as  console commands to create new controllers or areas.

**Comment by irustm** [comment]
Yes, such functionality is supported
https://github.com/alosaur/alosaur-schematics
only with node.js Soon it will be on deno
