### ISSUE TITLE
Will you guys gonna support webscoket recently?

### ISSUE THREAD

**Issue by Boyceman** [alosaur/alosaur#96]
I have an important project which is using alosaur. everything is going well. but i wanna support ws recently. so i wanna know if you guys will work on it recently. many thanks for your good work. it made me use deno simply. THANKS.

**Comment by irustm** [comment]
Thank you for your feedback.

Yes, to be implemented in order this month:

- websockets,
- SSE
- OpenAPI type reference
- microservice connector with WASM

**Comment by irustm** [comment]
Added WebSocket example:
https://github.com/alosaur/alosaur/tree/master/examples/ws
