### ISSUE TITLE
Compiler errors when running any alosaur app with Deno 1.4.6 with --unstable

### ISSUE THREAD

**Issue by cmd-johnson** [alosaur/alosaur#98]
Running any alosaur app with Deno@1.4.6 and the `--unstable` command line option set results in a bunch of Typescript errors like this (16 errors in total):

```
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  HTTPOptions,
  ~~~~~~~~~~~
    at https://deno.land/x/alosaur@v0.24.0/src/deps.ts:2:3
```

Steps to reproduce:

- clone the alosaur repository
- run `deno test -A --config ./src/tsconfig.lib.json --unstable`

`deno --version`:
```
deno 1.4.6
v8 8.7.220.3
typescript 4.0.3
```

I forked the repository and changed all the reported `export` statements to `export type`. My compiler now seems to be happy.

I'll put up a PR shortly.

**Comment by irustm** [comment]
thank you for this PR, released v0.24.1
